### ISSUE TITLE
Make default ip adress configurable

### ISSUE THREAD

**Issue by mrsteakhouse** [flatsiedatsie/webthings-network-presence-detection#11]
I'm running the gateway on a docker container on an odroid XU4. I was able do debug the code responsible for finding the local ip adress if the lan. Unfortunately the socket returns "0.0.0.0" and the adress gets set to "192.168.1.1". For pinging i need "192.168.**0**.1" and therefore no ping request are going through.

Please make the default adress configurable in the add-on settings page.
[This](https://github.com/flatsiedatsie/webthings-network-presence-detection/blob/6200bdd4b08a61efa0b6438dd703116f4e0c677a/pkg/util.py#L30) is the line in the code.

**Comment by mrsteakhouse** [comment]
I already made some changes for this issue. Can you please grant permissions to push my changes?
edit: nevermind, i now know how to github.

**Comment by flatsiedatsie** [comment]
Next time, please don't change all the print statements :-D
