### ISSUE TITLE
Error /bin/sh arp : not found

### ISSUE THREAD

**Issue by sibyaugustine** [flatsiedatsie/webthings-network-presence-detection#15]
I am getting the following error in the gateway, please help me to solve this problem
network-presence-detection: arp: not found

I am running using the following command, arp I am binding from the host machine(its not present in the container). This is working from the inside container and also working from python3 subprocess. 

> docker run \                                               
      -d \
      --rm 
      -v /usr/sbin/arp:/usr/sbin/arp \
      -v /path/to/shared/data:/home/node/.mozilla-iot \
      --net=host \
      --name mozilla-iot-gateway \
      mozillaiot/gateway:latest

#Testing

> docker exec -it mozilla-iot-gateway sh
> arp  ## yes its working
> python3 -c "import subprocess; subprocess.run('arp')" #working

**Comment by flatsiedatsie** [comment]
I am not familiar with Docker.

Have you installed Arp manually? The add-on doesn't do that for you.

If you have: what OS are you using?

Here you can see the call to arp being made. It's a simple "sudo arp" which it tries to run in the add-on directory. 
https://github.com/flatsiedatsie/webthings-network-presence-detection/blob/5777e4fd467666e4e0113b933e89a3832852caf7/pkg/util.py#L51

Perhaps it's a path issue?
Does `sudo arp` also work in your tests?

**Comment by flatsiedatsie** [comment]
Arp should now be built-in to the WebThings Gateway.
