### ISSUE TITLE
Very unstable detection

### ISSUE THREAD

**Issue by a9e78rauijasdf** [flatsiedatsie/webthings-network-presence-detection#16]
Hey.

First of all - this plugin is a must have! if only it behaved more stable. It varies *a lot* in when it "detects" a device. Could you maybe describe exactly how often it actually looks for devices?

My usecase: I want it to be able to turn off the lights when i leave a building, and then turn on the lights when I enter.

I have defined two rules:

1.  turn off lights, when it has been inactive in more than 1 minute.
2. turn on lights, when inactive in less that 1 minute.

Even with the device constantly online, "last detected" shows up to 2 minutes in "last seen" when testing (offlining the wifi device on purpuse). When online, the device is in fact constantly online (no wifi sleeping etc).

The "last seen"  switches to 99999  when the device status is "inactive" - even though it has been offline for just two minutes - a bit odd...?

Could you make it (ar)ping the devices much more often? it would increase reliability a lot :-)

Also - a bluetooth edition of this would be REALLY cool - but thats another thing ;) If I can figure out how, I will make it!

**Comment by flatsiedatsie** [comment]
You're not supposed to use it for something like 1 minute. The entire polling cycle itself, where it scans your entire network, lasts 3 minutes, easily.

**Comment by a9e78rauijasdf** [comment]
Howcome? why would it take three minutes to do an arp scan? it should be complete within seconds.

Especially if you would only have to poll select devices - you could easily arping every few seconds, to do real presense detection. Its not very useful, if the light takes three minutes to turn on when you enter the house ;)

**Comment by flatsiedatsie** [comment]
It's not that simple. But I'm working on a new version that will do scans way more often.
