### ISSUE TITLE
More info on discovered devices

### ISSUE THREAD

**Issue by dnhass** [flatsiedatsie/webthings-network-presence-detection#22]
Can your add-on provide more info when a device is discovered, such as the MAC address?  It's hard to identify cell phones, for example, when the only identification is the manufacturer.  Thanks.

**Comment by flatsiedatsie** [comment]
I purposefully wanted to avoid adding that, I thought it was a bit sensitive. 

But you could look at the settings on your phone and see what IP it has, and then compare that to the IP address the add-on provides?

**Comment by dnhass** [comment]
Thanks - understood.


On Thu, 16 Jan 2020 00:08:32 -0800
flatsiedatsie <notifications@github.com> wrote:

> I purposefully wanted to avoid adding that, I thought it was a bit
> sensitive. 
> 
> But you could look at the settings on your phone and see what IP it
> has, and then compare that to the IP address the add-on provides?
> 



-- 
Sent from Claws Mail on my home Pi 4

**Comment by dnhass** [comment]
I tested the addon with my phone and my wife's phone.  Both are Android
and I can't find info anywhere that suggests that Android phones change
their MAC addresses.  The addon switch our phones several times so it
doesn't appear to link to the MAC address.

Any suggestions?

Dave

On Thu, 16 Jan 2020 00:08:32 -0800
flatsiedatsie <notifications@github.com> wrote:

> I purposefully wanted to avoid adding that, I thought it was a bit
> sensitive. 
> 
> But you could look at the settings on your phone and see what IP it
> has, and then compare that to the IP address the add-on provides?
> 



-- 
Sent from Claws Mail on my home Pi 4

**Comment by flatsiedatsie** [comment]
That's.. odd. If you click on a thing you will be able to see it's internal ID in URL bar. Something like 

`presence-04b76d5d32cf`

That will actually tell you the MAC address, come to think of it.

The gateway works on the basis of this internal ID, as does the add-on. It doesn't change, so in theory it should be impossible for the phones to be switched.

Regular scanning is IP based. Perhaps it's something with the IP address switching. You could set up your router to always hand out the same IP address to a particular phone.

**Comment by flatsiedatsie** [comment]
I'm closing this issue. If there are others experiencing this as an issue, please let me know here.
