### ISSUE TITLE
"Target IP" unclear

### ISSUE THREAD

**Issue by IndexOverflow** [flatsiedatsie/webthings-network-presence-detection#23]
The description under Target IP reads

> Can be used to override the add-on to target a specific IP address range. For example, paste in 192.168.8.10 if you want to scan 192.168.8.2 through 192.168.8.254

This doesn't make sense to me. From looking at the code it appears this add-on is intended to scan ranges, but where is the logic in specifying a single IP if you are scanning an entire range? 

**Suggestion**: Make wording clearer, e.g use CIDR notation or allow "start" and "end" of range to be scanned.

**Comment by flatsiedatsie** [comment]
That's not a bad idea, but then users may think they could scan more subnets. Perhaps users could select a start and end range within one 255 range. I'll think about it.

The feature is for advanced users anyway, and was a feature request by someone else. Most users won't find it. If the value is empty, it defaults to scanning the range that the Raspberry Pi is in. For 99% of users this will be fine.

Thanks for sharing.

**Comment by IndexOverflow** [comment]
Fair enough, I see the argument that this is for advanced users. Having said that though I think most users of Webthings, in its current state at least, are developers / advanced _tinkerers_. E.g. for me it would never occur to run this on an actual Pi; I have it setup with Docker/ kubernetes. And even if I did have it on one of my Pis' they would be in a different sub net than my wi-fi clients anyway. 

Just some additional input to consider.

Ps. I still don't understand the logic for entering ".10" to scan the subnet from .2 to .254

**Comment by flatsiedatsie** [comment]
There's no logic to it :-)

My goal in creating this add-on was to make it functional on a Raspberry Pi.

If you create a pull request for code improvements, I'll be happy to add them. But for now the code works for my purposes.
