### ISSUE TITLE
Brute Force Scan Fails

### ISSUE THREAD

**Issue by damooooooooooh** [flatsiedatsie/webthings-network-presence-detection#24]
Some devices I was monitoring stopped reporting presence any more despite having same IP, MAC etc.  

I observed this following error: 

> network-presence-detection-adapter: Error doing brute force scan: dictionary changed size during iteration

Commenting  line 197 in presence-adapter.py allowed the brute force scan to complete again and redetect my devices........  Not sure what this error relates to as I don't have time to get my head into the workings of this adapter.

`# del self.previously_found[key]`

Maybe someone can have a look at the flow?  Might be a threading issue?

**Comment by flatsiedatsie** [comment]
Interesting. Should be fixable.

**Comment by flatsiedatsie** [comment]
Strange. The line is part of some code to remove devices from the found_devices list if they were never added to your things. WIthout that code, all devices that were on your network at some point would continue to show up in the 'found things' list in the Mozilla Gateway.

```
                    # Remove devices that haven't been spotted in a long time.
                    current_keys = self.previously_found.keys()
                    for key in current_keys:
                        try:
                            if time.time() - self.previously_found[key]['arpa_time'] > 86400 and key not in self.saved_devices:
                                if self.DEBUG:
                                    print("Removing devices from found devices list because it hasn't been spotted in a day, and it's not a device the user has imported.")
                                del self.previously_found[key]
                        except Exception as ex:
                            if self.DEBUG:
                                print("Could not remove old device: " + str(ex))
```
I guess the found-devices list was being modified during this proces, which should in theory be a freak occurance. Hmm, or perhaps it was removing multiple old devices.

The code is already in a try-catch mechanism, so shouldn't have stopped the addon from continuing. Did you get any other error messages around this one?

**Comment by flatsiedatsie** [comment]
It should be fixed in the next version.

**Comment by damooooooooooh** [comment]
Hi, were you able to reproduce it?

**Comment by flatsiedatsie** [comment]
no, but I just implemented it a bit differently. I'm testing it now.

**Comment by flatsiedatsie** [comment]
A new version has been released. Please let me know how this one works for you.

**Comment by damooooooooooh** [comment]
Issue seems to be closed with this update.
