### ISSUE TITLE
occasionally 'minutes ago last seen' jumps to an enormous value

### ISSUE THREAD

**Issue by cjcorrigan** [flatsiedatsie/webthings-network-presence-detection#25]
I use the network presence presence detection to monitor whether my phone is at home/connected to the wi-fi and trigger some rules on various values. What I occasionally notice is best displayed in the graph from the Logs screen of the Gateway.
![image](https://user-images.githubusercontent.com/417865/81079496-34758b00-8f22-11ea-8ca8-c8b521e99eb5.png)
At the moment, the webthing looks like this
![image](https://user-images.githubusercontent.com/417865/81079588-4fe09600-8f22-11ea-9963-47051d04bcaa.png)

Extracting a relevant section from the logs database . Note that this is fairly long to demonstrate that most of the time, the numbers are good, just sometimes weird.
id,date,value
5,1588309855502,0.0
5,1588310545680,1.0
5,1588310611299,0.0
5,1588310676848,1.0
5,1588310709660,0.0
5,1588310861137,1.0
5,1588310910347,2.0
5,1588310975888,3.0
5,1588311041401,4.0
5,1588311074160,0.0
5,1588311374277,1.0
5,1588311407070,0.0
5,1588311472577,1.0
5,1588311538140,2.0
5,1588311587348,3.0
5,1588311652876,4.0
5,1588311669262,0.0
5,1588311819607,1.0
5,1588311868763,2.0
5,1588311917999,0.0
5,1588312091226,1.0
5,1588312107592,0.0
5,1588312610488,1.0
5,1588312643302,0.0
5,1588312744599,1.0
5,1588312759175,0.0
5,1588312835540,1.0
5,1588312873578,0.0
5,1588312949308,1.0
5,1588312987232,0.0
5,1588314577528,1.0
5,1588314626767,2.0
5,1588314681046,0.0
5,1588314746616,1.0
5,1588314779407,0.0
5,1588314844937,1.0
5,1588314894138,2.0
5,1588314959718,3.0
5,1588314976143,0.0
5,1588315068298,1.0
5,1588315117471,0.0
5,1588315265011,1.0
5,1588315281371,0.0
5,1588315384472,19831.0
5,1588315395499,0.0
5,1588315524147,1.0
5,1588315556900,0.0
5,1588315785031,1.0
5,1588315834220,2.0
5,1588315899741,3.0
5,1588315965230,4.0
5,1588316014391,5.0
5,1588316019531,0.0
5,1588316090121,1.0
5,1588316139280,2.0
5,1588316204740,3.0
5,1588316237480,0.0
5,1588316605100,1.0
5,1588316642916,0.0
5,1588316713480,1.0
5,1588316778980,2.0
5,1588316828090,3.0
5,1588316877211,0.0
5,1588317023400,1.0
5,1588317072550,2.0
5,1588317138065,3.0
5,1588317203630,4.0
5,1588317252780,0.0
5,1588317333580,1.0
5,1588317399100,2.0
5,1588317448180,0.0
5,1588317872870,1.0
5,1588317877916,0.0
5,1588318045481,1.0
5,1588318094581,2.0
5,1588318160091,3.0
5,1588318192811,0.0
5,1588318263451,1.0
5,1588318312530,2.0
5,1588318378020,3.0
5,1588318410750,0.0
5,1588319291401,1.0
5,1588319340560,2.0
5,1588319405990,3.0
5,1588319427402,0.0
5,1588319612730,1.0
5,1588319645451,0.0
5,1588319803011,1.0
5,1588319852110,2.0
5,1588319917590,3.0
5,1588319983050,4.0
5,1588319999430,0.0
5,1588320286801,1.0
5,1588320352291,0.0
5,1588320596810,1.0
5,1588320634611,0.0
5,1588320759430,1.0
5,1588320808520,2.0
5,1588320873960,3.0
5,1588320911788,0.0
5,1588321291950,1.0
5,1588321341060,0.0
5,1588321406611,1.0
5,1588321472070,2.0
5,1588321493551,0.0
5,1588321699030,1.0
5,1588321748190,2.0
5,1588321813700,0.0
5,1588321949711,1.0
5,1588322015200,2.0
5,1588322064260,3.0
5,1588322096990,0.0
5,1588322401680,1.0
5,1588322467141,2.0
5,1588322499851,0.0
5,1588322565330,1.0
5,1588322614450,2.0
5,1588322679920,3.0
5,1588322717689,0.0
5,1588322879320,1.0
5,1588322928440,2.0
5,1588322993900,3.0
5,1588323042980,0.0
5,1588323178920,1.0
5,1588323228060,2.0
5,1588323293530,3.0
5,1588323359040,4.0
5,1588323396877,0.0
5,1588323575956,1.0
5,1588323625061,2.0
5,1588323690561,0.0
5,1588323897391,1.0
5,1588323946551,2.0
5,1588324011991,3.0
5,1588324077561,0.0
5,1588324174581,1.0
5,1588324240111,2.0
5,1588324289261,3.0
5,1588324327086,0.0
5,1588324789731,1.0
5,1588324855271,2.0
5,1588324904461,3.0
5,1588324920851,0.0
5,1588325116351,1.0
5,1588325165496,2.0
5,1588325170725,0.0
5,1588325251511,1.0
5,1588325316981,2.0
5,1588325349731,0.0
5,1588325415211,1.0
5,1588325431581,0.0
5,1588325579040,1.0
5,1588325584633,0.0
5,1588325720730,1.0
5,1588325786201,2.0
5,1588325835300,3.0
5,1588325900790,4.0
5,1588325938674,0.0
5,1588326052310,1.0
5,1588326101430,2.0
5,1588326122892,0.0
5,1588326340860,1.0
5,1588326406417,2.0
5,1588326455517,0.0
5,1588326558872,1.0
5,1588326575230,0.0
5,1588326645900,1.0
5,1588326695050,2.0
5,1588326727770,0.0
5,1588326793260,1.0
5,1588326842400,2.0
5,1588326891530,0.0
5,1588327141002,1.0
5,1588327190197,2.0
5,1588327195254,0.0
5,1588327271051,1.0
5,1588327320231,2.0
5,1588327325280,0.0
5,1588327494211,1.0
5,1588327499301,0.0
5,1588327699781,1.0
5,1588327716191,0.0
5,1588327879893,1.0
5,1588327929111,2.0
5,1588327994608,3.0
5,1588328060140,4.0
5,1588328109271,5.0
5,1588328125660,0.0
5,1588328191138,1.0
5,1588328240290,2.0
5,1588328305756,3.0
5,1588328945669,20057.0
5,1588329011139,20058.0
5,1588329043890,0.0
5,1588329201470,1.0
5,1588329250590,2.0
5,1588329304801,0.0
5,1588329423319,1.0
5,1588329472424,2.0
5,1588329537930,3.0
5,1588329603410,4.0
5,1588329608530,0.0

**Comment by flatsiedatsie** [comment]
Hmm. If a device is not found, then I believe there indeed is code to set it to 'an enormous value'. that was to indicate that the device is gone from the system I think. I'll have a look at it.

**Comment by flatsiedatsie** [comment]
I see a similar spike in my own logs.

**Comment by flatsiedatsie** [comment]
In the version I just uploaded it uses 'None' instead of 99999, so this might solve the issue.

**Comment by chas-iot** [comment]
I think this can be closed.
