### ISSUE TITLE
Can't detect our smartphones anymore

### ISSUE THREAD

**Issue by madb1lly** [flatsiedatsie/webthings-network-presence-detection#26]
Hi @flatsiedatsie,

I don't know exactly when this happened but during the last month or so the add-on can no longer detect our smartphones. Neither of our smartphones has had an update in the past few months and neither has the ADSL modem/router AFAIK. The Gateway is connected by LAN and the presence detector can see other Wifi devices no problem.

What can I do to get this working again?

Thanks 🙂

**Comment by flatsiedatsie** [comment]
I don't know. Are the other devices still reporting fine?

Mobile phones are more difficult to detect, and its the reason why the addon tries to use Arping.

Is this on a Raspberry Pi? Have you tried uninstalling and re-install the add-on? Have you tried a reboot? Have you enabled debug mode for the add-on and checked out the internal logs for any hints?

**Comment by madb1lly** [comment]
Hi @flatsiedatsie,
Thanks for the suggestions, here's the relevant parts (AFAICT) from the logs:

Before any changes, nothing relevant appears in the logs.

I think this is from when I removed the add-on and then rebooted.

> 2020-05-22 00:47:24.780 INFO   : Unloading PresenceAdapter
> 2020-05-22 00:47:28.467 INFO   : network-presence-detection-adapter: Time window value from settings page: 15
> 2020-05-22 00:47:28.525 INFO   : network-presence-detection-adapter: Error doing brute force scan: dictionary changed size during iteration
> 2020-05-22 00:47:28.556 INFO   : network-presence-detection-adapter: Clock thread error: dictionary changed size during iteration
> 2020-05-22 00:47:29.176 INFO   : Killing network-presence-detection-adapter plugin.
> 2020-05-22 00:47:32.011 INFO   : Loading add-on: network-presence-detection-adapter
> 2020-05-22 00:47:32.235 INFO   : Unhandled Rejection
> 2020-05-22 00:47:38.575 ERROR  : { Error: spawn ENOMEM
>     at ChildProcess.spawn (internal/child_process.js:366:11)
>     at spawn (child_process.js:551:9)
>     at startPromise.Settings.get.then (/home/pi/mozilla-iot/gateway/build/webpack:/src/plugin/plugin.js:644:1) errno: 'ENOMEM', code: 'ENOMEM', syscall: 'spawn' }

Some days later, I think I tried to reinstall the add-on or something:

> 2020-05-25 20:17:23.591 ERROR  : Failed to unload network-presence-detection-adapter properly: TypeError: Cannot read property 'send' of undefined

I think "Failed to unload" is this bug: https://github.com/mozilla-iot/gateway/issues/2497.

I think this is when I tried to re-install, remove, disable, the add-on? Sorry I can't remember:

> 2020-05-26 03:47:25.406 INFO   : Fetching add-on https://s3-us-west-2.amazonaws.com/mozilla-gateway-addons/network-presence-detection-adapter-0.1.2.tgz as /tmp/avKjWB/network-presence-detection-adapter.tar.gz
> 2020-05-26 03:47:29.214 INFO   : Expanding add-on /tmp/avKjWB/network-presence-detection-adapter.tar.gz
> 2020-05-26 03:47:35.612 ERROR  : Failed to unload network-presence-detection-adapter properly: TypeError: Cannot read property 'send' of undefined
> 2020-05-26 03:47:41.971 INFO   : Loading add-on: network-presence-detection-adapter
> 2020-05-26 03:47:42.221 INFO   : Unhandled Rejection
> 2020-05-26 03:47:42.272 ERROR  : { Error: spawn ENOMEM
>     at ChildProcess.spawn (internal/child_process.js:366:11)
>     at spawn (child_process.js:551:9)
>     at startPromise.Settings.get.then (/home/pi/mozilla-iot/gateway/build/webpack:/src/plugin/plugin.js:644:1) errno: 'ENOMEM', code: 'ENOMEM', syscall: 'spawn' }

Maybe this is when I tried to disable and reenable it?

> 2020-05-27 00:03:52.819 ERROR  : Failed to toggle add-on network-presence-detection-adapter
> 2020-05-27 00:03:52.931 ERROR  : TypeError: Cannot read property 'send' of undefined
>     at Plugin.sendMsg (/home/pi/mozilla-iot/gateway/build/webpack:/src/plugin/plugin.js:580:1)
>     at Plugin.unload (/home/pi/mozilla-iot/gateway/build/webpack:/src/plugin/plugin.js:737:1)
>     at AddonManager.unloadAddon (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-manager.js:963:1)
>     at AddonManager.disableAddon (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-manager.js:599:1)
> 2020-05-27 00:04:19.321 INFO   : Loading add-on: network-presence-detection-adapter
> 2020-05-27 00:04:19.521 INFO   : Unhandled Rejection
> 2020-05-27 00:04:19.552 ERROR  : { Error: spawn ENOMEM
>     at ChildProcess.spawn (internal/child_process.js:366:11)
>     at spawn (child_process.js:551:9)
>     at startPromise.Settings.get.then (/home/pi/mozilla-iot/gateway/build/webpack:/src/plugin/plugin.js:644:1) errno: 'ENOMEM', code: 'ENOMEM', syscall: 'spawn' }

And this, which I presume is when I enabled or disabled debug logging but can't remember:

> 2020-05-27 14:15:23.622 ERROR  : Failed to restart add-on network-presence-detection-adapter
> 2020-05-27 14:15:23.675 ERROR  : TypeError: Cannot read property 'send' of undefined
>     at Plugin.sendMsg (/home/pi/mozilla-iot/gateway/build/webpack:/src/plugin/plugin.js:580:1)
>     at Plugin.unload (/home/pi/mozilla-iot/gateway/build/webpack:/src/plugin/plugin.js:737:1)
>     at AddonManager.unloadAddon (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-manager.js:963:1)
>     at ./src/controllers/addons_controller.js.AddonsController.put (/home/pi/mozilla-iot/gateway/build/webpack:/src/controllers/addons_controller.js:111:1)

I tried to disable debugging but got this message when I clicked apply: 

> Errors
> 
>     undefined 400

But I think it does still disable debug logging because when I reload the page the box is unticked. I get the same message when I reenable it and the box is ticked on page reload.

Log entries which I can confirm correspond to the debug enable/disable are:

> 2020-05-27 14:39:44.521 ERROR  : Failed to restart add-on network-presence-detection-adapter
> 2020-05-27 14:39:44.552 ERROR  : TypeError: Cannot read property 'send' of undefined
>     at Plugin.sendMsg (/home/pi/mozilla-iot/gateway/build/webpack:/src/plugin/plugin.js:580:1)
>     at Plugin.unload (/home/pi/mozilla-iot/gateway/build/webpack:/src/plugin/plugin.js:737:1)
>     at AddonManager.unloadAddon (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-manager.js:963:1)
>     at ./src/controllers/addons_controller.js.AddonsController.put (/home/pi/mozilla-iot/gateway/build/webpack:/src/controllers/addons_controller.js:111:1)

On things page when I try to add a new device I don't get a message about the presence detector in the log, i.e. About to call startPairing.

I'm just in the middle of trying to remove and re-add the addon again but it's taking a while. If I get any new messages I'll post them here.

Cheers 🙂

**Comment by madb1lly** [comment]
Hi @flatsiedatsie,
I've no idea how, but it's now working! Smartphones are now detected again as well.

However, if there any of those error messages you'd like to look into in more detail please tell me and I'll see what I can do to replicate the conditions.

Cheers 🙂

**Comment by flatsiedatsie** [comment]
I recently created a fix. The add-on has probably auto-updated. 

Glad to hear it's working for you! :-)
