### ISSUE TITLE
Error doing brute force scan: name 'fdist1' is not defined

### ISSUE THREAD

**Issue by chas-iot** [flatsiedatsie/webthings-network-presence-detection#28]
The full message is 
2020-06-04 09:43:07.286 INFO   : network-presence-detection-adapter: Error doing brute force scan: name 'fdist1' is not defined
and was repeated 139 times over a duration of 0.1 seconds.

**Comment by damooooooooooh** [comment]
See Issue #24, this is likely a duplicate

**Comment by damooooooooooh** [comment]
My bad, looks like there was an issue fixed recently by he latest commit/release.
