### ISSUE TITLE
arp command is only functional on Linux

### ISSUE THREAD

**Issue by mrstegeman** [flatsiedatsie/webthings-network-presence-detection#3]
Right now, the add-on uses `sudo arp`. That will work fine on Linux (where password-less sudo is enabled), but not elsewhere. For instance on macOS, that yields this:

```
$ sudo arp
usage: arp [-n] [-i interface] hostname
       arp [-n] [-i interface] [-l] -a
       arp -d hostname [pub] [ifscope interface]
       arp -d [-i interface] -a
       arp -s hostname ether_addr [temp] [reject] [blackhole] [pub [only]] [ifscope interface]
       arp -S hostname ether_addr [temp] [reject] [blackhole] [pub [only]] [ifscope interface]
       arp -f filename
```

Is there a platform-agnostic arp library for Python you could use instead? For instance, on Node we use [local-devices](https://www.npmjs.com/package/local-devices).

**Comment by flatsiedatsie** [comment]
I didn't even realise it used sudo. It shouldn't have to, I purposefully wanted to avoid anything that required rights escalation. I recommend we remove the sudo! Would that solve the issue on mac?

I'll look into a library. I didn't find anything great so far though.

**Comment by flatsiedatsie** [comment]
I have removed the sudo.

**Comment by flatsiedatsie** [comment]
I have confirmed it works just fine without the sudo. My mac also has arp, and is gives usable results without sudo, so that should also work.

**Comment by mrstegeman** [comment]
If you use `arp -a`, you will get more consistent results.

On my Linux box:
```
gateway.local (192.168.86.182) at b8:27:eb:9d:0c:fe [ether] on enp2s0
```

On my Mac:
```
gateway.local (192.168.86.182) at b8:27:eb:9d:c:fe on en0 ifscope [ethernet]
```

**Comment by flatsiedatsie** [comment]
I did indeed switch to arp -a.

The entire add-on works differently now. It continuously scans the /24 IP range. 
- It first tries ping. 
- If that doesn't work it tries arping. If arping is not present, this has the same effect as being a scan that results in nothing. _Arping does require sudo._
- If it found an IP address it will use arp -a to find the mac-address and, ideally, a hostname.
- If there is no hostname is looks up a vendor name (based on the mac address) in a local table.

0.0.2 now has some new features, like 
- threading.
- Remembering which IP address had devices on them before, and going more thorough scans on those.
- It will do a thorough scan of the network every X scans, meaning it will do a ping+arping scan with a higher retry count.

- Storage of the json is done on every change of the main dictionary object.
- The vendor name is now shorter
- al devices now get a 'last seen' property which indicates how many minutes ago the device was last seen. It does this until it reaches the user-defined threshold.

Also new in 0.0.2: I've tested it a bit, and it seems to work ok.
