### ISSUE TITLE
Network Presence Add-on failing to start 0.11.0

### ISSUE THREAD

**Issue by malceore** [flatsiedatsie/webthings-network-presence-detection#32]
Hello, I recently upgraded my webthings Gateway to try some new features like this add-on. I installed it and attempted to add a new device. But no new device pops up in 'add device'. It also looks like when I enable and disable the add-on no separate process is started and in the logs I only see the below.
`
2020-09-22 08:20:03.238 INFO   : Killing network-presence-detection-adapter plugin.
2020-09-22 08:20:06.214 INFO   : Loading add-on: network-presence-detection-adapter
`

I am using python3 version 3.5, is this version too old? Additionally is there a log output somewhere so I can troubleshoot this?

**Comment by flatsiedatsie** [comment]
You can enable debuggin in the addon settings, and then check the internal logs. I would recommend updating to a fresh 0.12 gateway image if you want to be sure everything works ok.

**Comment by malceore** [comment]
I'm not getting any output with that flag. But also Yeelight isn't working and these are both Python so I'll chase that lead. Thanks!

**Comment by malceore** [comment]
Hello, so I wanted to try debugging this again before I end up building my own plugin for this purpose. I'm running gateway 0.11.0 and Python 3.5, when I install the plugin the gateway logs show "Loading add-on: network-presence-detection-adapter", but even with the debug logging enabled I do not seem to get any logging. Additionally I do not see a process thread running for this plugin after enabling it and I tried debugging the code but that seems to end in a checksum errors. 

Is there a certain version of Python that this works best with?

**Comment by malceore** [comment]
Okay I figured it out. Looks like I had the python add-on library for 0.12.0 installed, install 0.11.0 and tmy environment was having a websockets collision. Reinstalled 0.11.0 and now my Python Add-ons work perfectly! 

https://discourse.mozilla.org/t/update-to-0-10-broke-connection-to-all-of-my-iot-devices/48566/8
