### ISSUE TITLE
Time window

### ISSUE THREAD

**Issue by arfrater** [flatsiedatsie/webthings-network-presence-detection#9]
Hello, the time window setting is not been adhere to. I have set the time window to 5 minutes before the device is marked offline? 
![gateway1](https://user-images.githubusercontent.com/49191109/57563347-3a549100-73e0-11e9-8809-47d92effa6fd.png)

But the device is still showing active after 22 mins last seen even thou there is no IP in the details ?
![gateway2](https://user-images.githubusercontent.com/49191109/57563360-640db800-73e0-11e9-97f1-6e7ece14c55c.png)

Just turned on The WIFI on the device and now is showing active with the IP address in details and last seen 0 mins ago.
![Gateway3](https://user-images.githubusercontent.com/49191109/57563447-4ab93b80-73e1-11e9-8488-fd249836c5c3.png)

**Comment by flatsiedatsie** [comment]
Thank you, I will look into it. It might be that 5 minutes is too fast. It takes a few minutes to do each scan.

**Comment by flatsiedatsie** [comment]
I was unable to replicate the issue. Do you still experience it?
